[package]
name = "http_router"
version = "0.1.0"
authors = ["Алексей Карасев <karasev.alexey@gmail.com>"]

[lib]
doctest = false

[features]
unstable = []

[dependencies]
regex = "1"

[dev-dependencies]
rand = "0.5.5"
